################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the SuperH RISC engine Standard Toolchain toolchain
TC_INSTALL_DIR = c:\program files (x86)\renesas\hew_002\tools\renesas\sh\9_4_3

#####################################################
#
# Details:
#   Project: UnitTest
#   Configuration: SimDebug_SH-4A_Cycle_L
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.lib"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0="$(TC_INSTALL_DIR)\bin\libsrc.pak"

# Renesas SH C/C++ Compiler02 phase

UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE=shc.exe
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC0="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC1="..\UnitTest\SimDebug_SH-4A_Cycle_L\dbsct.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC1="..\UnitTest\typedefine.h"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC2="..\UnitTest\SimDebug_SH-4A_Cycle_L\lowsrc.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC2="$(TC_INSTALL_DIR)\include\string.h" "$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\stdio.h" "..\UnitTest\typedefine.h" "..\UnitTest\lowsrc.h"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC3="..\UnitTest\SimDebug_SH-4A_Cycle_L\resetprg.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC3="$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\umachine.h" "$(TC_INSTALL_DIR)\include\_h_c_lib.h" "..\UnitTest\typedefine.h" \
	"..\UnitTest\stacksct.h"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC4="..\UnitTest\SimDebug_SH-4A_Cycle_L\sample.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC5="..\UnitTest\SimDebug_SH-4A_Cycle_L\sbrk.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC5="$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\stdio.h" "..\UnitTest\typedefine.h" \
	"..\UnitTest\sbrk.h"

# Renesas SH Assembler03 phase

UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_EXE=asmsh.exe
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC0="..\UnitTest\SimDebug_SH-4A_Cycle_L\intprg.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_DEPFILESC0="..\UnitTest\vect.inc"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC1="..\UnitTest\SimDebug_SH-4A_Cycle_L\lowlvl.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC2="..\UnitTest\SimDebug_SH-4A_Cycle_L\vecttbl.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC3="..\UnitTest\SimDebug_SH-4A_Cycle_L\vhandler.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_DEPFILESC3="..\UnitTest\env.inc" "..\UnitTest\vect.inc"

# Renesas OptLinker04 phase

UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_EXE=LnkSpawn.exe
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_INFILESC0="..\UnitTest\SimDebug_SH-4A_Cycle_L\dbsct.obj" "..\UnitTest\SimDebug_SH-4A_Cycle_L\intprg.obj" \
	"..\UnitTest\SimDebug_SH-4A_Cycle_L\lowlvl.obj" "..\UnitTest\SimDebug_SH-4A_Cycle_L\lowsrc.obj" \
	"..\UnitTest\SimDebug_SH-4A_Cycle_L\resetprg.obj" "..\UnitTest\SimDebug_SH-4A_Cycle_L\sample.obj" \
	"..\UnitTest\SimDebug_SH-4A_Cycle_L\sbrk.obj" "..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.lib" \
	"..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.obj" "..\UnitTest\SimDebug_SH-4A_Cycle_L\vecttbl.obj" \
	"..\UnitTest\SimDebug_SH-4A_Cycle_L\vhandler.obj"
UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_OUTFILESC0="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.mot" "..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.abs" \
	"..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.map"

#######################
# nmake "all" statement

ALL:	UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_ENVC0 \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC0) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC1) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC2) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC3) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC4) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC5) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC0) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC1) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC2) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC3) \
	$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Library Generator01 phase
!MESSAGE

UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\bji\AppData\Local\Temp

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) : $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-output="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.lib"
-gbr=auto
-head=runtime,new,stdio,stdlib,string
<<

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC0) : "..\UnitTest\UnitTest.c"
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.obj"
-debug
-gbr=auto
"..\UnitTest\UnitTest.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC1) : "..\UnitTest\dbsct.c" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC1)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\dbsct.obj"
-debug
-gbr=auto
"..\UnitTest\dbsct.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC2) : "..\UnitTest\lowsrc.c" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC2)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\lowsrc.obj"
-debug
-gbr=auto
"..\UnitTest\lowsrc.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC3) : "..\UnitTest\resetprg.c" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC3)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\resetprg.obj"
-debug
-gbr=auto
"..\UnitTest\resetprg.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC4) : "..\UnitTest\sample.c"
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\sample.obj"
-debug
-gbr=auto
"..\UnitTest\sample.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_OUTFILESC5) : "..\UnitTest\sbrk.c" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_DEPFILESC5)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4a
-endian=little
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\sbrk.obj"
-debug
-gbr=auto
"..\UnitTest\sbrk.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas SH Assembler03 phase
!MESSAGE

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC0) : "..\UnitTest\intprg.src" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_DEPFILESC0)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\UnitTest\intprg.src"
-cpu=sh4a
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\intprg.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC1) : "..\UnitTest\lowlvl.src"
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\UnitTest\lowlvl.src"
-cpu=sh4a
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\lowlvl.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC2) : "..\UnitTest\vecttbl.src" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_DEPFILESC0)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\UnitTest\vecttbl.src"
-cpu=sh4a
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\vecttbl.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_OUTFILESC3) : "..\UnitTest\vhandler.src" $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_DEPFILESC3)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\UnitTest\vhandler.src"
-cpu=sh4a
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\UnitTest\SimDebug_SH-4A_Cycle_L\vhandler.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_OUTFILESC0) : $(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_INFILESC0)
	"$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(UNITTEST_SIMDEBUG_SH4A_CYCLE_L_OPTLINKER04_EXE)" -subcommand=<<
noprelink
rom D=R
nomessage 
list "..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.map"
nooptimize
-start=PResetPRG/01000,P,C,C$BSEC,C$DSEC,D/02000,INTHandler,VECTTBL,INTTBL,IntPRG/080000400,RSTHandler/0A0000000,B/0E5000000,PIntPRG/0E500A000,S/0E5010000,R/0E501E000
nologo
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\dbsct.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\intprg.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\lowlvl.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\lowsrc.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\resetprg.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\sample.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\sbrk.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\vecttbl.obj"
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\vhandler.obj"
-library="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.lib"
-output="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.abs"
end
-input="..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.abs"
form stype
output "..\UnitTest\SimDebug_SH-4A_Cycle_L\UnitTest.mot"
-exit

<<

