/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Fri, May 28, 2021                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :SH7780                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 20
